global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "myfinance"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["my-finance-app:5050"]
        labels:
          application: "myfinance-api"
          environment: "docker"
