server:
  port: 5050

app:
  security:
    admin-emails: ${ADMIN_EMAILS}

  cache:
    ttl:
      accounts: 3600
      categories: 86400
      users: 3600
      dashboards: 300
      goals: 3600
      transactions: 300

spring:
  application:
    name: myfinance-api

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5051}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MyFinanceHikariPool

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:5052}

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: ${ISSUER_URI}

      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI}
            user-name-attribute: preferred_username

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

  metrics:
    tags:
      application: myfinance-api

    distribution:
      percentiles-histogram:
        http.server.requests: true

      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99

    enable:
      jvm: true
      hikaricp: true
      process: true
      system: true