server:
  port: 5050

spring:
  application:
    name: myfinance-api

  datasource:
    url: jdbc:postgresql://localhost:5051/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 5052

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile

springdoc:
  swagger-ui:
    path: /swagger-ui.html
