services:
  my-finance-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-finance-app
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - myfinance-network
    depends_on:
      postgres:
        condition: service_healthy
      dragonfly:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: db-my-finance
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myfinance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  dragonfly:
    image: ghcr.io/dragonflydb/dragonfly:v1.37.0
    container_name: myfinance-dragonfly
    restart: unless-stopped
    volumes:
      - dragonfly_data:/data
    command:
      - "--dbfilename=dump"
      - "--dir=/data"
    networks:
      - myfinance-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: myfinance-prometheus
    restart: unless-stopped
    ports:
      - "5054:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.retention.size=2GB'
    networks:
      - myfinance-network

  grafana:
    image: grafana/grafana:10.4.2
    container_name: myfinance-grafana
    restart: unless-stopped
    ports:
      - "5055:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - myfinance-network


  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower-my-finance
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --interval
      - "300"
    networks:
      - myfinance-network


networks:
  myfinance-network:
    driver: bridge

volumes:
  postgres_data:
  dragonfly_data:
  prometheus_data:
  grafana_data:
