services:
  my-finance-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-finance-app
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - myfinance-network
    depends_on:
      postgres:
        condition: service_healthy
      dragonfly:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: db-my-finance
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myfinance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  dragonfly:
    image: docker.io/dragonflydb/dragonfly:v1.27.1
    container_name: myfinance-dragonfly
    restart: unless-stopped
    volumes:
      - dragonfly_data:/data
    command:
      - "--dbfilename=dump"
      - "--dir=/data"
    networks:
      - myfinance-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  myfinance-network:
    driver: bridge

volumes:
  postgres_data:
  dragonfly_data: