name: Deploy Automático para Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o Código do GitHub
        uses: actions/checkout@v4

      - name: Configurando o Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compilando o Spring Boot (Maven)
        working-directory: ./myfinance-api
        run: mvn clean package -DskipTests

      - name: Preparando emulador ARM
        uses: docker/setup-qemu-action@v3

      - name: Configurando Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Criando Imagem e Mandando pro Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ./myfinance-api
          platforms: linux/arm64
          push: true
          tags: |
            gustavosdaniel/my-finance-app:latest
            gustavosdaniel/my-finance-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy na Máquina 2 (Oracle Cloud)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd /home/ubuntu/myfinance-app
            docker compose pull
            docker compose up -d
            docker compose ps
            sleep 30
            curl -f http://localhost:5050/actuator/health || exit 1